@ECHO OFF

REM Programa Que Ejeplifica el Uso Practico de la Sentencia CHOICE

ECHO ==================================
ECHO         .:MENU PRINCIPAL:.
ECHO 1.-     EJECUTAR PROGRAMA 1
ECHO 2.-     EJECUTAR PROGRAMA 2
ECHO 3.-     EJECUTAR PROGRAMA 3
ECHO ==================================

CHOICE /C 123 /N /M "ELIGE UNA OPCION: "

REM ERRORLEVEL ALMACENA LA OPCION QUE EL USUARIO SELECIONO
REM VERIFICA LO QUE SELECIONO EL USUARIO
IF ERRORLEVEL 3 GOTO PROG3
IF ERRORLEVEL 2 GOTO PROG2
IF ERRORLEVEL 1 GOTO PROG1

REM SI EL USUARIO DIGITA OTRA OPCION
ECHO OPCION INVALIDA
GOTO SALIDA

:PROG1
ECHO SELECIONASTE EJECUTAR EL PROGRAMA 1 .......
GOTO SALIDA

:PROG2
ECHO SELECIONASTE EJECUTAR EL PROGRAMA 2 .......
GOTO SALIDA

:PROG3
ECHO SELECIONASTE EJECUTAR EL PROGRAMA 3 .......
GOTO SALIDA

:SALIDA
ECHO.
ECHO FIN DEL PROGRAMA.................
PAUSE
CLS