@ECHO OFF

REM --USO DE LA SENTENCIA CHOICE--
REM Esta Herramienta permite que los Usuarios selecionen un elemento de una Lista de opciones y devuelve el indice
REM de la opción Selecionada

ECHO SELECIONE UNA OPCION PARA CONTINUAR
CHOICE /C yn
PAUSE
CLS


ECHO SELECIONE UNA OPCION ANTES DE 10 SEGUNDO, SI NO SE AUTO SELECIONARA Y
REM LA Opcion /T Determina el Tiempo de Espera en Segundos
REM LA Opcion /C Determina LAS OPCIONES QUE SE MUESTRAN PARA ELEGIR
REM LA Opcion /CS Determina QUE NO SE DISTINGA ENTRE MINUSCULAS Y MAYUSCULAS
REM LA Opcion /D ESTABLECE LA OPCION POR DEFECTO
REM LA Opcion /M ESTABLECE EL MENSAJE QUE SE LE MOSTRARA AL USUARIO
CHOICE /T 10 /C ync /CS /D y /M "PRECIONE Y PARA SI, N PARA NO O C PARA CANCELAR"